name: CI/CD
on:
  push:
    branches:
      - main
      - beta
      - renovate/**
  pull_request: null
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  lint-commit-messages:
    uses: vidavidorra/.github/.github/workflows/lint-commit-messages.yml@83b254fde3a73f1835299994d551de7d3c23dff2 # v8.1.13
  lint:
    uses: vidavidorra/.github/.github/workflows/node-lint.yml@83b254fde3a73f1835299994d551de7d3c23dff2 # v8.1.13
  build:
    uses: vidavidorra/.github/.github/workflows/node-build.yml@83b254fde3a73f1835299994d551de7d3c23dff2 # v8.1.13
  release:
    uses: vidavidorra/.github/.github/workflows/release.yml@83b254fde3a73f1835299994d551de7d3c23dff2 # v8.1.13
    needs:
      - lint-commit-messages
      - lint
      - build
    secrets:
      privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
