name: CI/CD
on:
  push:
    branches:
      - main
      - beta
      - renovate/**
  pull_request: null
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  lint-commit-messages:
    uses: vidavidorra/.github/.github/workflows/lint-commit-messages.yml@2694afc21ede4760dfc7a13061caa14fa247312f # v8.1.12
  lint:
    uses: vidavidorra/.github/.github/workflows/node-lint.yml@2694afc21ede4760dfc7a13061caa14fa247312f # v8.1.12
  build:
    uses: vidavidorra/.github/.github/workflows/node-build.yml@2694afc21ede4760dfc7a13061caa14fa247312f # v8.1.12
  release:
    uses: vidavidorra/.github/.github/workflows/release.yml@2694afc21ede4760dfc7a13061caa14fa247312f # v8.1.12
    needs:
      - lint-commit-messages
      - lint
      - build
    secrets:
      privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
