name: CI/CD
on:
  push:
    branches:
      - main
      - beta
      - renovate/**
  pull_request: null
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  lint-commit-messages:
    uses: vidavidorra/.github/.github/workflows/lint-commit-messages.yml@a20dedb518e531d281a34c6db20042926ef60eda # v8.1.16
  lint:
    uses: vidavidorra/.github/.github/workflows/node-lint.yml@a20dedb518e531d281a34c6db20042926ef60eda # v8.1.16
  build:
    uses: vidavidorra/.github/.github/workflows/node-build.yml@a20dedb518e531d281a34c6db20042926ef60eda # v8.1.16
  release:
    uses: vidavidorra/.github/.github/workflows/release.yml@a20dedb518e531d281a34c6db20042926ef60eda # v8.1.16
    needs:
      - lint-commit-messages
      - lint
      - build
    secrets:
      privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
